library(tidyverse)
library(limSolve)
library(abind)
args = commandArgs(trailingOnly=TRUE)
mychr           = as.character(args[1])
myRfile         = as.character(args[2])
mydir           = as.character(args[3])
myoutdir        = as.character(args[4])
COV_SMOOTH_KB   = as.integer(args[5])   # covariance smoothing half-window in kb (0 = off)
FREQ_SMOOTH_KB  = as.integer(args[6])   # frequency smoothing half-window in kb  (0 = off)

design.df = read.table(myRfile)
source("scripts/scan_functions.R")
filein   = paste0(mydir, "/R.haps.", mychr, ".out.rds")
mydirout = paste0(mydir, "/", myoutdir)
dir.create(file.path(mydir, myoutdir))
fileout               = paste0(mydirout, "/", myoutdir, ".scan.", mychr, ".txt")
fileout_meansBySample = paste0(mydirout, "/", myoutdir, ".meansBySample.", mychr, ".txt")
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
source("scripts/haps2scan.freqsmooth.code.R")
