library(tidyverse)
library(limSolve)
library(abind)
args = commandArgs(trailingOnly=TRUE)
mychr=as.character(args[1])
myRfile = as.character(args[2])
mydir = as.character(args[3])
myoutdir = as.character(args[4])
design.df = read.table(myRfile)
script_dir <- dirname(normalizePath(sub("--file=", "", grep("--file=", commandArgs(FALSE), value=TRUE))))
source(file.path(script_dir, "scan_functions.R"))
filein=paste0(mydir,"/R.haps.",mychr,".out.rds")
mydirout=paste0(mydir,"/",myoutdir)
dir.create(file.path(mydir,myoutdir))
fileout=paste0(mydirout,"/",myoutdir,".scan.",mychr,".txt")
fileout_meansBySample=paste0(mydirout,"/",myoutdir,".meansBySample.",mychr,".txt")
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
source(file.path(script_dir, "haps2scan.Apr2025.code.R"))

