library(tidyverse)
library(limSolve)
library(data.table)
library(dtplyr)
# library(tidyfast)
args = commandArgs(trailingOnly=TRUE)
mychr=as.character(args[1])
myparfile = as.character(args[2])
mydir = as.character(args[3])

source(myparfile)
filein=paste0(mydir,"/RefAlt.",mychr,".txt")
rdsfile=paste0(mydir,"/R.haps.",mychr,".rds")
fileout=paste0(mydir,"/R.haps.",mychr,".out.rds")
script_dir <- dirname(normalizePath(sub("--file=", "", grep("--file=", commandArgs(FALSE), value=TRUE))))
source(file.path(script_dir, "REFALT2haps.code.R"))

